# ~/.tmuxinator/project.yml
# Usage: txs project <path-to-the-project-folder>

<% project_path = File.absolute_path(@args[0]) %>

name: <%= File.basename(project_path) %>
root: <%= project_path %>
startup_pane: 1

windows:
  - console:
      layout: main-vertical
      panes:
        - #empty
        - #empty
        - #empty
  - editor: nvim
